CREATE DATABASE IF NOT EXISTS ipiggconect
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ipiggconect;

CREATE TABLE IF NOT EXISTS mural (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  subtitle TEXT,
  publish_date DATE NOT NULL,
  link TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
